version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - 3310:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080